En la programación de computadoras digitales, una operación bit a bit opera en uno o más patrones de bits o números binarios
 al nivel de sus bits individuales. Es una acción rápida y simple, respaldada directamente por el procesador, y se utiliza para manipular
  valores para comparaciones y cálculos.

En los procesadores simples de bajo costo, por lo general, las operaciones a nivel de bits son sustancialmente más rápidas que la división, 
varias veces más rápidas que la multiplicación y, a veces, significativamente más rápidas que la suma. Con sus tuberías de instrucción más largas y
 otras opciones de diseño arquitectónico,
 las operaciones bit a bit suelen utilizar menos energía debido al uso reducido de los recursos.

 